In [4]:
import numpy as np
a = np.int8(25)
print(type(a))

<class 'numpy.int8'>


In [11]:
np.iinfo(np.int64)
#np.iinfo(a)

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [14]:
b = np.uint8(124)
print(b)
print(type(b))
np.iinfo(b)

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [18]:
a = np.int32(1000)
print(a)
print(type(a))
a = np.int32(2056)
print(a)
print(type(a))

1000
<class 'numpy.int32'>
2056
<class 'numpy.int32'>


In [20]:
a = np.int32(1000)
b = a + 25
print(b)
print(type(b))

1025
<class 'numpy.int32'>


In [21]:
a = np.int32(1000)
b = np.int8(25)
c = a + b
print(c)
print(type(c))

1025
<class 'numpy.int32'>


In [22]:
a = np.int8(260)
print(a)

4


C:\Users\User\AppData\Local\Temp\ipykernel_49688\464275206.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 260 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a = np.int8(260)


In [25]:
a = np.int32(2147483610)
b = np.int32(2147483605)
print(a, b)
print(np.int64(a) + np.int64(b))

2147483610 2147483605
4294967215


In [10]:
import numpy as np
print(np.finfo(np.float16))
print(np.finfo(np.float32))
print(np.finfo(np.float64))


Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------

Machine parameters for float64
---

In [11]:
print(np.sctypeDict)
print(len(np.sctypeDict))

{'?': <class 'numpy.bool_'>, 0: <class 'numpy.bool_'>, 'byte': <class 'numpy.int8'>, 'b': <class 'numpy.int8'>, 1: <class 'numpy.int8'>, 'ubyte': <class 'numpy.uint8'>, 'B': <class 'numpy.uint8'>, 2: <class 'numpy.uint8'>, 'short': <class 'numpy.int16'>, 'h': <class 'numpy.int16'>, 3: <class 'numpy.int16'>, 'ushort': <class 'numpy.uint16'>, 'H': <class 'numpy.uint16'>, 4: <class 'numpy.uint16'>, 'i': <class 'numpy.intc'>, 5: <class 'numpy.intc'>, 'uint': <class 'numpy.uint32'>, 'I': <class 'numpy.uintc'>, 6: <class 'numpy.uintc'>, 'intp': <class 'numpy.int64'>, 'p': <class 'numpy.int64'>, 9: <class 'numpy.int64'>, 'uintp': <class 'numpy.uint64'>, 'P': <class 'numpy.uint64'>, 10: <class 'numpy.uint64'>, 'long': <class 'numpy.int32'>, 'l': <class 'numpy.int32'>, 7: <class 'numpy.int32'>, 'ulong': <class 'numpy.uint32'>, 'L': <class 'numpy.uint32'>, 8: <class 'numpy.uint32'>, 'longlong': <class 'numpy.int64'>, 'q': <class 'numpy.int64'>, 'ulonglong': <class 'numpy.uint64'>, 'Q': <class 'n

In [17]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [20]:
a = np.bool_(a)
print(type(a))

<class 'numpy.bool_'>


In [ ]:
print(np.bool)

In [21]:
a = np.uint8(-456)
print(a)

56


C:\Users\User\AppData\Local\Temp\ipykernel_30036\3325698846.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -456 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a = np.uint8(-456)


In [4]:
import numpy as np

arr = np.array([1,5,2,9,10])
arr.dtype
#print(type(arr))

dtype('int32')

In [5]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [10]:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [12]:
arr = np.float64(arr)
arr

array([ 1.,  5., 12.,  9., 10.])

In [20]:
import numpy as np


np.finfo(dtype=np.float32)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

In [11]:
def domain_name(url):
    start_list = ['https://www.', 'http://www.', 'http://', 'https://', 'www.']
    for word in start_list:
        if word in url:
            url = url.replace(word, '')
    domain_name = '' 
    for letter in url:       
        if letter != '.':
            domain_name += letter
        else:
            break
    return domain_name
print(domain_name("http://github.com/carbonfive/raygun"))

github


In [6]:

url = 'http://github.com/carbonfive/raygun'
start_list = ['https://www.', 'http://www.', 'http://', 'https://', 'www.']
for word in start_list:
    if word in url:
        url = url.replace(word, '')
print(url)

github.com/carbonfive/raygun


In [ ]:
text = 'abcd'
text

In [10]:
import numpy as np
arr = np.array([1, 5, 2, 9, 10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

nd_arr.itemsize

2

In [11]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [13]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
print(zeros_3d)

(5, 4, 3)
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [17]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [23]:
arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)

0.1


In [7]:
import numpy as np

arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step, 2))

0.45


In [3]:
import numpy as np
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [12]:
arr = np.arange(8)
arr.shape = (2, 4)
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [16]:
arr = np.linspace(1, 2, 6)
print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


In [26]:
nd_arr = np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
print(nd_arr)
nd_arr[1][2]
nd_arr[1, 2]
nd_arr[:2, 2]
nd_arr[1:, 2:4]
nd_arr[:, 2:4]
nd_arr[:2]

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [2]:
import numpy as np
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
print(arr_new)

[23 12 45 12 23  4 15  3]
[ 3  4 12 12 15 23 23 45]


In [3]:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
print(arr)

None
[ 3  4 12 12 15 23 23 45]


In [8]:
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
sum(roots)
np.isnan(roots)
roots[np.isnan(roots)] = 0
sum(roots)

C:\Users\User\AppData\Local\Temp\ipykernel_33580\3513894826.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


6.732050807568877

In [10]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [14]:
vec = np.arange(5)
vec ** 4

array([  0,   1,  16,  81, 256], dtype=int32)

In [15]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 > vec2

array([False, False,  True, False])

In [16]:
vec = np.array([14,15,9,26,53,5,89])

vec <= 26

array([ True,  True,  True,  True, False,  True, False])

In [18]:
vec = np.array([3, 4])
length = np.sqrt(np.sum(vec **2))
length = np.linalg.norm(vec)
print(length)

5.0


In [19]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1-vec2) ** 2))
print(distance)

12.206555615733702


In [20]:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

12.206555615733702

In [22]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
#scalar_product = np.sum(vec1 * vec2)
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0

In [1]:
import numpy as np
vec = np.array([2,7,18,28,18,1,8,4])
vec.mean()

10.75

In [20]:
np.random.rand()*100

24.803829276918655

In [25]:
np.random.rand(5)*100

array([25.95537144, 65.75106752, 48.56153269, 31.26740546, 53.90743929])

In [26]:
np.random.rand(2, 3)

array([[0.62690742, 0.4741676 , 0.9066244 ],
       [0.67747011, 0.91914911, 0.54630296]])

In [28]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.16516447, 0.1732193 , 0.14402662, 0.35064705],
       [0.4745952 , 0.13730736, 0.75020955, 0.80438296],
       [0.84972089, 0.83208395, 0.95279923, 0.55181464]])

In [29]:
shape = (2, 3)
np.random.sample(shape)

array([[0.58907508, 0.22290516, 0.65870128],
       [0.138234  , 0.3123332 , 0.31571796]])

In [39]:
np.random.uniform(-30, 50, size=(2, 5))

array([[ 16.33173598,   1.15143536,  25.70497031,  -7.70793824,
         49.67498161],
       [ 47.4910235 ,  35.54271068, -29.90274534,   1.14366106,
         42.53027512]])

In [59]:
np.random.randint(4, 6, size=(2,4))

array([[4, 4, 5, 5],
       [5, 4, 5, 5]])

In [61]:
arr = np.arange(6)
print(arr)
print(np.random.shuffle(arr))

[0 1 2 3 4 5]
None


In [64]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffle = np.random.permutation(playlist)
print(shuffle)
print(playlist)

['Deep Purple' 'Pink Floyd' 'The Beatles' 'ACDC']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [65]:
np.random.permutation(10)

array([8, 4, 7, 5, 3, 9, 6, 0, 1, 2])

In [74]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']

choice = np.random.choice(workers, size=3, replace=False)
print(choice)

['Nikita' 'Maria' 'Kate']


In [79]:
choice = np.random.choice([1,2,3,4,5,6], size=10)
print(choice)

[3 4 3 1 1 6 2 4 2 1]


In [88]:
np.random.seed(23)
np.random.randint(10, size=12)

array([3, 6, 8, 9, 6, 8, 7, 9, 3, 6, 1, 2])

In [2]:
import numpy as np
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

In [28]:
array = np.zeros((5,5))
array[1::2, ::2] = 1
array[::2, 1::2] = 1
array

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

In [31]:
seed = np.random.seed(np.random.randint(4294967296, dtype=np.int64))
seed

: 

In [6]:
import numpy as np

vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
vectors = (vec1, vec2, vec3)
print(vectors)
min_dist = np.linalg.norm(vec1 - vec2)


(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))


In [9]:
import numpy as np
vec1 = np.array([19, 242, 14, 152, 142, 1000])
vec1.mean()

261.5

In [7]:
seconds = 1

hours = '00' + str(seconds // 3600)
minutes = '00' + str(seconds % 3600 // 60) 
sec =  '00' + str(seconds % 3600 % 60)

print(f'{hours[-2:]}:{minutes[-2:]}:{sec[-2:]}')

00:00:01


In [4]:
source_array = [1, 1, 5, 11, 2, 11, 111, 0]
list(filter(lambda x: x is not None, [index if value % 2 !=0 else None for index, value in enumerate(source_array)]))
sorted(list(filter(lambda x: x is not None, [i if i % 2 != 0 else None for i in source_array])))

[1, 1, 5, 11, 11, 111]